/**
 * AI Nowcast page — displays hyper-local short-range forecast
 * generated by Claude from station data + model guidance.
 */
import { useState, useEffect, useCallback } from "react";
import { useWeatherData } from "../context/WeatherDataContext.tsx";
import { useIsMobile } from "../hooks/useIsMobile.ts";
import { resolveTimezone } from "../utils/timezone.ts";
import {
  fetchNowcastVerifications,
  fetchNowcastKnowledge,
  updateNowcastKnowledge,
  fetchNWSAlerts,
} from "../api/client.ts";
import type {
  NowcastVerification,
  NowcastKnowledgeEntry,
  NWSActiveAlert,
} from "../api/types.ts";

const cardStyle: React.CSSProperties = {
  background: "var(--color-bg-card)",
  borderRadius: "var(--gauge-border-radius)",
  border: "1px solid var(--color-border)",
  padding: "20px",
  marginBottom: "16px",
};

const sectionTitle: React.CSSProperties = {
  margin: "0 0 12px 0",
  fontSize: "16px",
  fontFamily: "var(--font-heading)",
  color: "var(--color-text)",
};

function normalizeConfidence(c: string): string {
  const upper = (c ?? "").toUpperCase();
  if (upper.startsWith("HIGH")) return "HIGH";
  if (upper.startsWith("MEDIUM")) return "MEDIUM";
  if (upper.startsWith("LOW")) return "LOW";
  return upper;
}

function confidenceColor(c: string): string {
  switch (normalizeConfidence(c)) {
    case "HIGH":
      return "var(--color-success)";
    case "MEDIUM":
      return "var(--color-warning, #f59e0b)";
    case "LOW":
      return "var(--color-danger)";
    default:
      return "var(--color-text-muted)";
  }
}

function ConfidenceBadge({ level }: { level: string }) {
  const label = normalizeConfidence(level);
  return (
    <span
      style={{
        display: "inline-block",
        fontSize: "11px",
        fontFamily: "var(--font-body)",
        fontWeight: 600,
        padding: "2px 8px",
        borderRadius: "4px",
        background: confidenceColor(level),
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: "0.5px",
      }}
    >
      {label}
    </span>
  );
}

function RadarImg({ src, alt, label, isMobile }: { src: string; alt: string; label: string; isMobile: boolean }) {
  const [failed, setFailed] = useState(false);
  // Reset error state when src changes (new nowcast generated).
  useEffect(() => { setFailed(false); }, [src]);
  if (failed) return null;
  return (
    <div style={{ textAlign: "center" }}>
      <div style={{ position: "relative", display: "inline-block" }}>
        <img
          src={src}
          alt={alt}
          style={{
            width: isMobile ? "100%" : "240px",
            height: "auto",
            borderRadius: "8px",
            border: "1px solid var(--color-border)",
            display: "block",
          }}
          onError={() => setFailed(true)}
        />
        {/* Station crosshair */}
        <svg
          style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
            pointerEvents: "none",
          }}
          width="20"
          height="20"
          viewBox="0 0 20 20"
        >
          <circle cx="10" cy="10" r="4" fill="none" stroke="white" strokeWidth="2.5" />
          <circle cx="10" cy="10" r="4" fill="none" stroke="red" strokeWidth="1.5" />
          <line x1="10" y1="0" x2="10" y2="6" stroke="white" strokeWidth="2.5" />
          <line x1="10" y1="0" x2="10" y2="6" stroke="red" strokeWidth="1.5" />
          <line x1="10" y1="14" x2="10" y2="20" stroke="white" strokeWidth="2.5" />
          <line x1="10" y1="14" x2="10" y2="20" stroke="red" strokeWidth="1.5" />
          <line x1="0" y1="10" x2="6" y2="10" stroke="white" strokeWidth="2.5" />
          <line x1="0" y1="10" x2="6" y2="10" stroke="red" strokeWidth="1.5" />
          <line x1="14" y1="10" x2="20" y2="10" stroke="white" strokeWidth="2.5" />
          <line x1="14" y1="10" x2="20" y2="10" stroke="red" strokeWidth="1.5" />
        </svg>
      </div>
      <div
        style={{
          fontSize: "11px",
          fontFamily: "var(--font-body)",
          color: "var(--color-text-muted)",
          marginTop: "4px",
        }}
      >
        {label}
      </div>
    </div>
  );
}

function timeAgo(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime();
  const minutes = Math.floor(diff / 60000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

function formatLocalTime(isoString: string): string {
  const tz = resolveTimezone();
  return new Date(isoString).toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
    timeZone: tz,
  });
}

function ElementCard({
  label,
  element,
}: {
  label: string;
  element?: { forecast: string; confidence: string; timing?: string };
}) {
  if (!element) return null;
  return (
    <div style={cardStyle}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "10px",
        }}
      >
        <h4 style={{ ...sectionTitle, margin: 0 }}>{label}</h4>
        <ConfidenceBadge level={element.confidence} />
      </div>
      <p
        style={{
          margin: 0,
          fontSize: "14px",
          fontFamily: "var(--font-body)",
          color: "var(--color-text)",
          lineHeight: 1.5,
        }}
      >
        {element.forecast}
      </p>
      {element.timing && (
        <p
          style={{
            margin: "8px 0 0 0",
            fontSize: "13px",
            fontFamily: "var(--font-mono)",
            color: "var(--color-text-secondary)",
          }}
        >
          Timing: {element.timing}
        </p>
      )}
    </div>
  );
}

function accuracyColor(score: number | null): string {
  if (score === null) return "var(--color-text-muted)";
  if (score >= 0.8) return "var(--color-success)";
  if (score >= 0.5) return "var(--color-warning, #f59e0b)";
  return "var(--color-danger)";
}

function CollapsibleSection({
  title,
  expanded,
  onToggle,
  children,
}: {
  title: string;
  expanded: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div style={{ ...cardStyle, padding: 0 }}>
      <div
        onClick={onToggle}
        style={{
          padding: "14px 20px",
          cursor: "pointer",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          userSelect: "none",
        }}
      >
        <h4 style={{ ...sectionTitle, margin: 0 }}>{title}</h4>
        <span
          style={{
            fontSize: "12px",
            color: "var(--color-text-muted)",
            transition: "transform 0.2s",
            transform: expanded ? "rotate(90deg)" : "rotate(0deg)",
            display: "inline-block",
          }}
        >
          {"\u25B6"}
        </span>
      </div>
      {expanded && (
        <div style={{ padding: "0 20px 16px 20px" }}>{children}</div>
      )}
    </div>
  );
}

function AccuracyBar({ score }: { score: number | null }) {
  return (
    <div
      style={{
        height: "6px",
        borderRadius: "3px",
        background: "var(--color-bg-secondary)",
        width: "60px",
        overflow: "hidden",
        flexShrink: 0,
      }}
    >
      <div
        style={{
          height: "100%",
          width: `${(score ?? 0) * 100}%`,
          background: accuracyColor(score),
          borderRadius: "3px",
        }}
      />
    </div>
  );
}

function CategoryBadge({ category }: { category: string }) {
  return (
    <span
      style={{
        display: "inline-block",
        fontSize: "11px",
        fontFamily: "var(--font-body)",
        padding: "2px 6px",
        borderRadius: "3px",
        background: "var(--color-bg-secondary)",
        color: "var(--color-text-muted)",
        textTransform: "lowercase",
      }}
    >
      {category}
    </span>
  );
}

export default function Nowcast() {
  const { nowcast, triggerNowcast, alertMode } = useWeatherData();
  const isMobile = useIsMobile();

  // Verification state
  const [verificationsExpanded, setVerificationsExpanded] = useState(false);
  const [verifications, setVerifications] = useState<NowcastVerification[]>([]);
  const [verificationsLoading, setVerificationsLoading] = useState(false);

  const loadVerifications = useCallback(() => {
    setVerificationsLoading(true);
    fetchNowcastVerifications(20)
      .then(setVerifications)
      .catch(() => {})
      .finally(() => setVerificationsLoading(false));
  }, []);

  useEffect(() => {
    if (verificationsExpanded) loadVerifications();
  }, [verificationsExpanded, loadVerifications]);

  // NWS alerts state
  const [nwsAlerts, setNwsAlerts] = useState<NWSActiveAlert[]>([]);
  const [alertsExpanded, setAlertsExpanded] = useState<Set<string>>(new Set());

  useEffect(() => {
    let cancelled = false;
    const poll = () => {
      fetchNWSAlerts()
        .then((r) => { if (!cancelled) setNwsAlerts(r.alerts); })
        .catch(() => {});
    };
    poll();
    const interval = alertMode ? 60_000 : 180_000;
    const id = setInterval(poll, interval);
    return () => { cancelled = true; clearInterval(id); };
  }, [alertMode]);

  // Knowledge state
  const [knowledgeExpanded, setKnowledgeExpanded] = useState(false);
  const [knowledge, setKnowledge] = useState<NowcastKnowledgeEntry[]>([]);
  const [knowledgeLoading, setKnowledgeLoading] = useState(false);

  const loadKnowledge = useCallback(() => {
    setKnowledgeLoading(true);
    fetchNowcastKnowledge()
      .then(setKnowledge)
      .catch(() => {})
      .finally(() => setKnowledgeLoading(false));
  }, []);

  useEffect(() => {
    if (knowledgeExpanded) loadKnowledge();
  }, [knowledgeExpanded, loadKnowledge]);

  const handleKnowledgeAction = useCallback(
    (id: number, status: "accepted" | "rejected") => {
      updateNowcastKnowledge(id, status)
        .then((updated) => {
          setKnowledge((prev) =>
            prev.map((e) => (e.id === updated.id ? updated : e)),
          );
        })
        .catch(() => {});
    },
    [],
  );

  if (!nowcast) {
    return (
      <div style={{ display: "flex", flexDirection: "column", flex: 1, minHeight: 0 }}>
        <div style={{ flexShrink: 0, padding: "24px 24px 0" }}>
          <h2
            style={{
              margin: "0 0 16px 0",
              fontSize: "24px",
              fontFamily: "var(--font-heading)",
              color: "var(--color-text)",
            }}
          >
            AI Nowcast
          </h2>
        </div>
        <div style={{ flex: 1, overflowY: "auto", minHeight: 0, padding: "0 24px 24px" }}>
        <div style={cardStyle}>
          <div
            style={{
              padding: "32px 0",
              textAlign: "center",
              color: "var(--color-text-muted)",
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              lineHeight: 1.6,
            }}
          >
            No nowcast available. Enable the AI Nowcast service in Settings
            and configure your Anthropic API key to get started.
          </div>
        </div>
        </div>
      </div>
    );
  }

  const elements = nowcast.elements || {};

  return (
    <div style={{ display: "flex", flexDirection: "column", flex: 1, minHeight: 0 }}>
      {/* Header */}
      <div
        style={{
          flexShrink: 0,
          padding: "24px 24px 0",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "8px",
          marginBottom: "16px",
        }}
      >
        <h2
          style={{
            margin: 0,
            fontSize: "24px",
            fontFamily: "var(--font-heading)",
            color: "var(--color-text)",
          }}
        >
          AI Nowcast
        </h2>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "12px",
          }}
        >
          <span
            style={{
              fontSize: "12px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-muted)",
            }}
          >
            {nowcast.valid_from && nowcast.valid_until
              ? `${formatLocalTime(nowcast.valid_from)} – ${formatLocalTime(nowcast.valid_until)}`
              : `Updated ${timeAgo(nowcast.created_at)}`}
          </span>
          <button
            onClick={triggerNowcast}
            style={{
              fontFamily: "var(--font-body)",
              fontSize: "13px",
              padding: "6px 14px",
              borderRadius: "6px",
              border: "1px solid var(--color-border)",
              background: "var(--color-bg-secondary)",
              color: "var(--color-text)",
              cursor: "pointer",
            }}
          >
            Refresh
          </button>
        </div>
      </div>

      <div style={{ flex: 1, overflowY: "auto", minHeight: 0, padding: "0 24px 24px" }}>

      {/* NWS Active Alerts */}
      {nwsAlerts.length > 0 && nwsAlerts.map((alert) => {
        const isWarning = alert.severity === "Extreme" || alert.severity === "Severe";
        const isWatch = alert.severity === "Moderate";
        const bg = isWarning
          ? "var(--color-danger, #dc2626)"
          : isWatch
            ? "#d97706"
            : "#ca8a04";
        const expanded = alertsExpanded.has(alert.alert_id);
        return (
          <div
            key={alert.alert_id}
            style={{
              background: bg,
              color: "#fff",
              borderRadius: "var(--gauge-border-radius)",
              padding: isMobile ? "10px 12px" : "12px 16px",
              marginBottom: "12px",
              cursor: "pointer",
              fontSize: "14px",
              fontFamily: "var(--font-body)",
            }}
            onClick={() => setAlertsExpanded((prev) => {
              const next = new Set(prev);
              if (next.has(alert.alert_id)) next.delete(alert.alert_id);
              else next.add(alert.alert_id);
              return next;
            })}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontWeight: 700, fontSize: "15px" }}>
                {alert.event}
              </span>
              <span style={{ fontSize: "11px", opacity: 0.85 }}>
                {alert.sender_name}
              </span>
            </div>
            <div style={{ fontSize: "13px", marginTop: "4px", opacity: 0.95 }}>
              {alert.headline}
            </div>
            {expanded && (
              <div style={{ marginTop: "10px", fontSize: "13px", lineHeight: 1.5, opacity: 0.95 }}>
                {alert.instruction && (
                  <div style={{ marginBottom: "8px" }}>
                    <strong>Action:</strong> {alert.instruction}
                  </div>
                )}
                <div style={{ whiteSpace: "pre-wrap" }}>{alert.description}</div>
                <div style={{ marginTop: "8px", fontSize: "11px", opacity: 0.7 }}>
                  Onset: {new Date(alert.onset).toLocaleString()} | Expires: {new Date(alert.expires).toLocaleString()}
                </div>
              </div>
            )}
            {!expanded && (
              <div style={{ fontSize: "11px", marginTop: "4px", opacity: 0.7 }}>
                Tap for details
              </div>
            )}
          </div>
        );
      })}

      {/* Severe Weather Correlation (AI analysis — distinct from raw NWS alerts above) */}
      {nowcast.severe_weather && (() => {
        const sw = nowcast.severe_weather as {
          threat_level?: string;
          primary_threat?: string;
          summary?: string;
          distance_miles?: number | null;
          bearing?: string | null;
          estimated_arrival?: string | null;
          local_evidence?: string[];
          recommended_action?: string;
        };
        const level = (sw.threat_level || "WARNING").toUpperCase();
        const bg =
          level === "EMERGENCY"
            ? "#7f1d1d"
            : level === "WARNING"
              ? "var(--color-danger, #dc2626)"
              : "#d97706";
        return (
          <div
            style={{
              background: bg,
              color: "#fff",
              borderRadius: "var(--gauge-border-radius)",
              padding: isMobile ? "14px 14px" : "16px 20px",
              marginBottom: "16px",
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              lineHeight: 1.5,
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "10px",
                marginBottom: "8px",
              }}
            >
              <span
                style={{
                  fontSize: "12px",
                  fontWeight: 700,
                  padding: "2px 8px",
                  borderRadius: "4px",
                  background: "rgba(255,255,255,0.2)",
                  letterSpacing: "0.5px",
                }}
              >
                {level}
              </span>
              <span style={{ fontWeight: 700, fontSize: "16px" }}>
                {sw.primary_threat}
              </span>
            </div>
            <div style={{ marginBottom: "10px" }}>{sw.summary}</div>
            {(sw.distance_miles != null || sw.estimated_arrival) && (
              <div
                style={{
                  fontSize: "13px",
                  marginBottom: "8px",
                  opacity: 0.9,
                }}
              >
                {sw.distance_miles != null && sw.bearing && (
                  <span>Distance: ~{sw.distance_miles} mi {sw.bearing}</span>
                )}
                {sw.distance_miles != null && sw.estimated_arrival && " | "}
                {sw.estimated_arrival && (
                  <span>ETA: {sw.estimated_arrival}</span>
                )}
              </div>
            )}
            {sw.local_evidence && sw.local_evidence.length > 0 && (
              <div style={{ fontSize: "13px", marginBottom: "10px" }}>
                <div style={{ fontWeight: 600, marginBottom: "4px", opacity: 0.85 }}>
                  Local Evidence:
                </div>
                {sw.local_evidence.map((e, i) => (
                  <div key={i} style={{ paddingLeft: "12px", opacity: 0.9 }}>
                    - {e}
                  </div>
                ))}
              </div>
            )}
            {sw.recommended_action && (
              <div
                style={{
                  fontWeight: 700,
                  fontSize: "15px",
                  borderTop: "1px solid rgba(255,255,255,0.3)",
                  paddingTop: "10px",
                  marginTop: "4px",
                }}
              >
                ACTION: {sw.recommended_action}
              </div>
            )}
          </div>
        );
      })()}

      {/* Summary */}
      <div style={{ ...cardStyle, borderLeft: "4px solid var(--color-accent)" }}>
        <p
          style={{
            margin: 0,
            fontSize: "16px",
            fontFamily: "var(--font-body)",
            color: "var(--color-text)",
            lineHeight: 1.6,
          }}
        >
          {nowcast.summary}
        </p>
      </div>

      {/* Element cards */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: isMobile
            ? "1fr"
            : "repeat(auto-fit, minmax(min(300px, 100%), 1fr))",
          gap: "0 16px",
        }}
      >
        <ElementCard label="Temperature" element={elements.temperature} />
        <ElementCard label="Precipitation" element={elements.precipitation} />
        <ElementCard label="Wind" element={elements.wind} />
        <ElementCard label="Sky Conditions" element={elements.sky} />
      </div>

      {/* Radar */}
      {nowcast.radar_analysis && (() => {
        const cacheBust = encodeURIComponent(nowcast.created_at || "");
        return (
          <div style={cardStyle}>
            <h4 style={sectionTitle}>Radar Analysis</h4>
            <div
              style={{
                display: isMobile ? "block" : "flex",
                gap: "16px",
                alignItems: "flex-start",
              }}
            >
              <div
                style={{
                  display: "flex",
                  flexDirection: isMobile ? "column" : "row",
                  gap: "12px",
                  flexShrink: 0,
                  marginBottom: isMobile ? "12px" : 0,
                }}
              >
                <RadarImg
                  src={`/api/nowcast/radar?t=${cacheBust}`}
                  alt="NEXRAD composite reflectivity"
                  label="Reflectivity"
                  isMobile={isMobile}
                />
                <RadarImg
                  src={`/api/nowcast/radar/nexrad_velocity?t=${cacheBust}`}
                  alt="Storm Relative Velocity"
                  label="Velocity"
                  isMobile={isMobile}
                />
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: "14px",
                  fontFamily: "var(--font-body)",
                  color: "var(--color-text)",
                  lineHeight: 1.5,
                }}
              >
                {nowcast.radar_analysis}
              </p>
            </div>
          </div>
        );
      })()}

      {/* Special conditions */}
      {elements.special && (
        <div
          style={{
            ...cardStyle,
            borderLeft: "4px solid var(--color-danger)",
            background: "var(--color-bg-card)",
          }}
        >
          <h4 style={{ ...sectionTitle, color: "var(--color-danger)" }}>
            Special Conditions
          </h4>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text)",
              lineHeight: 1.5,
            }}
          >
            {elements.special}
          </p>
        </div>
      )}

      {/* Farming Impact */}
      {nowcast.farming_impact && (
        <div style={cardStyle}>
          <h4 style={sectionTitle}>Farming Impact</h4>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text)",
              lineHeight: 1.5,
            }}
          >
            {nowcast.farming_impact}
          </p>
        </div>
      )}

      {/* Model Comparison */}
      {nowcast.current_vs_model && (
        <div style={cardStyle}>
          <h4 style={sectionTitle}>Observations vs. Model</h4>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-secondary)",
              lineHeight: 1.5,
            }}
          >
            {nowcast.current_vs_model}
          </p>
        </div>
      )}

      {/* Prediction Accuracy */}
      <CollapsibleSection
        title="Prediction Accuracy"
        expanded={verificationsExpanded}
        onToggle={() => setVerificationsExpanded((v) => !v)}
      >
        {verificationsLoading ? (
          <p
            style={{
              margin: 0,
              fontSize: "13px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-muted)",
            }}
          >
            Loading...
          </p>
        ) : verifications.length === 0 ? (
          <p
            style={{
              margin: 0,
              fontSize: "13px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-muted)",
            }}
          >
            No verification data yet. Predictions are verified automatically
            after the forecast window expires.
          </p>
        ) : (
          (() => {
            const grouped: Record<number, NowcastVerification[]> = {};
            for (const v of verifications) {
              (grouped[v.nowcast_id] ||= []).push(v);
            }
            return Object.entries(grouped).map(([id, items]) => (
              <div key={id} style={{ marginBottom: "12px" }}>
                <div
                  style={{
                    fontSize: "12px",
                    fontFamily: "var(--font-body)",
                    color: "var(--color-text-muted)",
                    marginBottom: "6px",
                  }}
                >
                  Nowcast #{id}{" "}
                  {items[0]?.verified_at &&
                    `(verified ${timeAgo(items[0].verified_at)})`}
                </div>
                {items
                  .filter((v) => v.element !== "system")
                  .map((v) => (
                    <div
                      key={v.id}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "10px",
                        padding: "4px 0",
                        fontSize: "13px",
                        fontFamily: "var(--font-body)",
                      }}
                    >
                      <span
                        style={{
                          width: "90px",
                          flexShrink: 0,
                          color: "var(--color-text)",
                          textTransform: "capitalize",
                        }}
                      >
                        {v.element}
                      </span>
                      <AccuracyBar score={v.accuracy_score} />
                      <span
                        style={{
                          width: "36px",
                          flexShrink: 0,
                          fontFamily: "var(--font-mono)",
                          fontSize: "12px",
                          color: accuracyColor(v.accuracy_score),
                          fontWeight: 600,
                        }}
                      >
                        {v.accuracy_score !== null
                          ? `${Math.round(v.accuracy_score * 100)}%`
                          : "—"}
                      </span>
                      <span
                        style={{
                          fontSize: "12px",
                          color: "var(--color-text-muted)",
                          overflow: "hidden",
                          textOverflow: "ellipsis",
                          whiteSpace: "nowrap",
                        }}
                      >
                        {v.notes || `${v.predicted} → ${v.actual}`}
                      </span>
                    </div>
                  ))}
                {items.find((v) => v.element === "system") && (
                  <div
                    style={{
                      fontSize: "12px",
                      fontFamily: "var(--font-body)",
                      color: "var(--color-text-muted)",
                      fontStyle: "italic",
                      padding: "4px 0",
                    }}
                  >
                    {items.find((v) => v.element === "system")?.notes ||
                      "Verification skipped"}
                  </div>
                )}
              </div>
            ));
          })()
        )}
      </CollapsibleSection>

      {/* Knowledge Base */}
      <CollapsibleSection
        title="Knowledge Base"
        expanded={knowledgeExpanded}
        onToggle={() => setKnowledgeExpanded((v) => !v)}
      >
        {knowledgeLoading ? (
          <p
            style={{
              margin: 0,
              fontSize: "13px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-muted)",
            }}
          >
            Loading...
          </p>
        ) : knowledge.length === 0 ? (
          <p
            style={{
              margin: 0,
              fontSize: "13px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-muted)",
            }}
          >
            No knowledge entries yet. The AI will propose insights as it learns
            your station's patterns.
          </p>
        ) : (
          <>
            {/* Pending entries */}
            {knowledge
              .filter((e) => e.status === "pending")
              .map((entry) => (
                <div
                  key={entry.id}
                  style={{
                    borderLeft: "3px solid var(--color-warning, #f59e0b)",
                    padding: "8px 12px",
                    marginBottom: "8px",
                    borderRadius: "0 4px 4px 0",
                    background: "var(--color-bg-secondary)",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                      marginBottom: "6px",
                    }}
                  >
                    <CategoryBadge category={entry.category} />
                    <span
                      style={{
                        fontSize: "11px",
                        fontFamily: "var(--font-body)",
                        color: "var(--color-text-muted)",
                      }}
                    >
                      {entry.source} &middot;{" "}
                      {entry.created_at && timeAgo(entry.created_at)}
                    </span>
                  </div>
                  <p
                    style={{
                      margin: "0 0 8px 0",
                      fontSize: "13px",
                      fontFamily: "var(--font-body)",
                      color: "var(--color-text)",
                      lineHeight: 1.4,
                    }}
                  >
                    {entry.content}
                  </p>
                  {entry.recommendation && (
                    <p
                      style={{
                        margin: "0 0 8px 0",
                        fontSize: "12px",
                        fontFamily: "var(--font-body)",
                        fontStyle: "italic",
                        color: "var(--color-text-secondary)",
                        lineHeight: 1.4,
                      }}
                    >
                      {entry.recommendation}
                    </p>
                  )}
                  <div style={{ display: "flex", gap: "8px" }}>
                    <button
                      onClick={() =>
                        handleKnowledgeAction(entry.id, "accepted")
                      }
                      style={{
                        fontSize: "12px",
                        fontFamily: "var(--font-body)",
                        padding: "3px 10px",
                        borderRadius: "4px",
                        border: "none",
                        background: "var(--color-success)",
                        color: "#fff",
                        cursor: "pointer",
                      }}
                    >
                      Accept
                    </button>
                    <button
                      onClick={() =>
                        handleKnowledgeAction(entry.id, "rejected")
                      }
                      style={{
                        fontSize: "12px",
                        fontFamily: "var(--font-body)",
                        padding: "3px 10px",
                        borderRadius: "4px",
                        border: "1px solid var(--color-border)",
                        background: "transparent",
                        color: "var(--color-text-muted)",
                        cursor: "pointer",
                      }}
                    >
                      Reject
                    </button>
                  </div>
                </div>
              ))}

            {/* Accepted entries */}
            {knowledge
              .filter((e) => e.status === "accepted")
              .map((entry) => (
                <div
                  key={entry.id}
                  style={{
                    borderLeft: "3px solid var(--color-success)",
                    padding: "8px 12px",
                    marginBottom: "8px",
                    borderRadius: "0 4px 4px 0",
                    opacity: 0.7,
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                      marginBottom: "4px",
                    }}
                  >
                    <CategoryBadge category={entry.category} />
                    <span
                      style={{
                        fontSize: "11px",
                        fontFamily: "var(--font-body)",
                        color: "var(--color-text-muted)",
                      }}
                    >
                      accepted
                      {entry.reviewed_at &&
                        ` ${timeAgo(entry.reviewed_at)}`}
                    </span>
                  </div>
                  <p
                    style={{
                      margin: 0,
                      fontSize: "13px",
                      fontFamily: "var(--font-body)",
                      color: "var(--color-text-secondary)",
                      lineHeight: 1.4,
                    }}
                  >
                    {entry.content}
                  </p>
                </div>
              ))}
          </>
        )}
      </CollapsibleSection>

      {/* Footer: data quality & metadata */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "8px",
          marginTop: "8px",
          fontSize: "12px",
          fontFamily: "var(--font-body)",
          color: "var(--color-text-muted)",
        }}
      >
        <span>
          Sources: {nowcast.sources_used?.join(", ") || "local station"}
        </span>
        <span>
          Model: {nowcast.model_used}{!nowcast.model_used?.startsWith("claude-") && " (fallback)"} | Tokens: {nowcast.input_tokens}
          /{nowcast.output_tokens}
        </span>
      </div>
      </div>
    </div>
  );
}
